### ISSUE TITLE
MutationMapper of 3dhotspots not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cancerhotspots#72]

**Comment by onursumer** [comment]
Seems like we already switched to `https` for 3d hotspots, but it is still accessing http://www.cbioportal.org/getPfamSequence.json, which is not secure. 

A quick fix might be to get it by proxy. Though it might be better to switch to Genome Nexus in the long run, since we may want to disable this endpoint on the portal side.

**Comment by jjgao** [comment]
@onursumer or should we use genomenexus data?

**Comment by jjgao** [comment]
@onursumer let's switch to genome nexus, if it's easy.

**Comment by onursumer** [comment]
@jjgao it is a bit tricky to make legacy mutation mapper compatible with the genome nexus endpoints, especially g2s may require some effort. I'd rather refactor cancer hotspot as a react application and use the standalone mutation mapper library as a long term solution.

**Comment by onursumer** [comment]
Seems like 3D viewer is still broken due to `https`, we need to fix that part too.
